## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Glass Home Studio | Custom Stained Glass | Oak Park + Chicago"
theme = "hugo-story"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Custom-made stained glass art at affordable prices in Oak Park and Chicago area.  Repairs, custom fittings, new construction, man caves, custom designs"
  logo = "images/banner.jpg"
  favicon = true
